---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@1d2a18056f2122b7f49c2e8aacb48c40cb6eaab9 # v1.24.0
    permissions:
      contents: read
      packages: read
      statuses: write
