---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@fc872ebc6ac6bb28fa73a2e83f9f354faad9b5b7 # v1.40.6
    permissions:
      contents: write
