---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@72b03607b365fcf968aa1d99f7864f0282e72e63 # v1.26.0
    permissions:
      contents: write
