---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@bb265ccce6562fcb1ad4ae85a4aacc72de332652 # v1.20.0
    permissions:
      contents: write
