---
name: semantic-pr

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  semantic-pr:
    uses: hugoh/gh-workflows/.github/workflows/semantic-pr.yml@c95078d6578bc039453fc9c865a0bc651dc00982 # v1.40.7
    permissions:
      pull-requests: read
