---
name: semantic-pr

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  semantic-pr:
    uses: hugoh/gh-workflows/.github/workflows/semantic-pr.yml@fc872ebc6ac6bb28fa73a2e83f9f354faad9b5b7 # v1.40.6
    permissions:
      pull-requests: read
